#!/bin/bash

echo "=========================================="
echo "📋 HƯỚNG DẪN APPLY SUPABASE SCHEMA"
echo "=========================================="
echo ""
echo "Bạn cần chạy các lệnh sau:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BƯỚC 1: Copy file schema"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "scp /root/toolxprint/supabase-schema.sql root@103.175.248.173:/root/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BƯỚC 2: SSH vào Supabase VPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "ssh root@103.175.248.173"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BƯỚC 3: Apply schema (chạy trên VPS Supabase)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /root"
echo "CONTAINER=\$(docker ps | grep postgres | awk '{print \$1}')"
echo "docker cp supabase-schema.sql \$CONTAINER:/tmp/schema.sql"
echo "docker exec -i \$CONTAINER psql -U postgres -d postgres -f /tmp/schema.sql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BƯỚC 4: Verify (optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "docker exec -i \$CONTAINER psql -U postgres -d postgres -c '\\dt public.*'"
echo ""
echo "=========================================="
echo ""
echo "Hoặc nếu bạn có quyền sudo, chạy lệnh này:"
echo ""
echo "sudo -u postgres psql -d postgres -f /root/supabase-schema.sql"
echo ""
echo "=========================================="
echo ""
echo "Sau khi apply xong, test bằng:"
echo ""
echo "curl http://157.66.80.125/supabase/rest/v1/profiles \\"
echo "  -H 'apikey: eyJhbGciOiAiSFMyNTYiLCAidHlwIjogIkpXVCJ9.eyJyb2xlIjogImFub24iLCAiaXNzIjogInN1cGFiYXNlIiwgImlhdCI6IDE3NzIyNDc1NzUsICJleHAiOiAyMDg3NjA3NTc1fQ.beUXcmOQqbsgHtjKnjcKI8D03LLwVF3VRRjxXkiCyJ0'"
echo ""
echo "=========================================="
