#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "  QUICK DEBUG - Scale Mode"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "Vui lòng làm theo:"
echo ""
echo "1. Mở browser: http://localhost:3000"
echo "2. Hard refresh: Ctrl+Shift+R"
echo "3. Vào ImpositionAdvancedPage"
echo "4. Upload: test-landscape-2000x1000.png"
echo "5. Set: Item 100x100mm, Scale 50%"
echo "6. Mở Console (F12)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Kiểm tra Console Log:"
echo ""
echo "Tìm: '🔍 FRONTEND SCALE DEBUG'"
echo ""
echo "Phải thấy:"
echo "  scaledPx: { w: 591, h: 296 }"
echo "  scaledMm: { w: \"50.04\", h: \"25.06\" }"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Nếu KHÔNG thấy log:"
echo "  → Frontend chưa update, cần hard refresh lại"
echo ""
echo "Nếu thấy log NHƯNG số khác:"
echo "  → Copy log và gửi cho tôi"
echo ""
echo "Nếu preview/output không đúng:"
echo "  → Mô tả: ảnh quá lớn hay quá nhỏ?"
echo "  → So sánh: preview vs output khác nhau như thế nào?"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Sau khi Generate PDF, check backend log:"
echo ""
tail -50 /root/toolxprint/python-service.log | grep -A5 "BACKEND SCALE" | head -10 || echo "  (Chưa có log backend)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
