#!/bin/bash

echo "======================================"
echo "📦 Supabase Backend Setup Package"
echo "======================================"
echo ""
echo "Files to copy to Supabase VPS (103.175.248.173):"
echo "  1. supabase-schema.sql"
echo "  2. apply-supabase-schema.sh"
echo ""
echo "Commands to run:"
echo ""
echo "# 1. Copy files to Supabase VPS"
echo "scp supabase-schema.sql root@103.175.248.173:/root/"
echo "scp apply-supabase-schema.sh root@103.175.248.173:/root/"
echo ""
echo "# 2. SSH to Supabase VPS"
echo "ssh root@103.175.248.173"
echo ""
echo "# 3. Apply schema"
echo "cd /root"
echo "chmod +x apply-supabase-schema.sh"
echo "./apply-supabase-schema.sh"
echo ""
echo "======================================"
echo "✅ After applying schema, your backend will have:"
echo "======================================"
echo ""
echo "📊 Tables:"
echo "  - profiles (user profiles)"
echo "  - projects (design projects)"
echo "  - files (file management)"
echo "  - customers (customer management)"
echo "  - quotes (quotations)"
echo "  - invoices (invoicing)"
echo "  - products (products/services)"
echo "  - paper_prices (paper pricing)"
echo "  - templates (design templates)"
echo "  - activity_logs (activity tracking)"
echo ""
echo "🔐 Security:"
echo "  - Row Level Security enabled"
echo "  - Users can only access their own data"
echo ""
echo "🎯 Features:"
echo "  - Realtime updates"
echo "  - File storage"
echo "  - Auto-generated UUIDs"
echo "  - Auto-updated timestamps"
echo ""
echo "📝 Usage in code:"
echo "  import { useProjects } from './hooks/useSupabase';"
echo "  const { projects, createProject } = useProjects();"
echo ""
echo "======================================"
echo "📖 Full documentation: SUPABASE_BACKEND_COMPLETE.md"
echo "======================================"
