"""
Simple Flask API Server for PDF Generation and AI Image Processing
Port: 3005
"""

import os
import sys
import json
import time
import uuid
import threading
import io
import base64
import logging
from datetime import datetime
from flask import Flask, request, jsonify, send_file, Response, g

logger = logging.getLogger(__name__)
from flask_cors import CORS

# Add current directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import existing modules
from solver import calculate_layout
from processor import generate_pdf, generate_pdf_multipage, generate_svg, render_preview_thumbnail, UPLOADS_DIR

# Try to import AI modules
try:
    import torch
    from rembg import remove
    from PIL import Image
    import io
    AI_AVAILABLE = True
    print("[AI] AI modules loaded successfully")
except ImportError as e:
    AI_AVAILABLE = False
    print(f"[AI] AI modules not available: {e}")

# Try to import iopaint
try:
    # Skip iopaint for now as it may have compatibility issues
    # from iopaint.api import Api
    # from iopaint.schema import Config
    IOPAINT_AVAILABLE = False
    print("[AI] IOPaint skipped for compatibility")
except ImportError as e:
    IOPAINT_AVAILABLE = False
    print(f"[AI] IOPaint not available: {e}")

app = Flask(__name__)
from flask_cors import CORS
CORS(app)

from imposition_storage import register_storage_routes
register_storage_routes(app)

# Mock file class for PDF generation  
class MockFile:
    def __init__(self, path, filename):
        self.path = path
        self.filename = filename
    def save(self, path):
        import shutil
        shutil.copy2(self.path, path)

# Configuration
app.config['MAX_CONTENT_LENGTH'] = 2 * 1024 * 1024 * 1024  # 2GB max file size
app.config['UPLOAD_FOLDER'] = UPLOADS_DIR

def create_demo_pdf():
    """Create a demo PDF with actual content for testing"""
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    from reportlab.lib.colors import red, blue, green, black
    from io import BytesIO
    
    # Create PDF in memory
    pdf_buffer = BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=(210 * mm, 297 * mm))  # A4
    
    # Set title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 250 * mm, "Demo PDF - Label Designer")
    
    # Draw some sample rectangles to simulate labels
    c.setStrokeColor(red)
    c.setFillColor(blue)
    c.rect(20 * mm, 200 * mm, 50 * mm, 30 * mm, fill=1, stroke=1)
    c.setFillColor(black)
    c.drawString(25 * mm, 210 * mm, "Label 1")
    
    c.setStrokeColor(green)
    c.setFillColor(red)
    c.rect(80 * mm, 200 * mm, 50 * mm, 30 * mm, fill=1, stroke=1)
    c.setFillColor(black)
    c.drawString(85 * mm, 210 * mm, "Label 2")
    
    c.setStrokeColor(blue)
    c.setFillColor(green)
    c.rect(20 * mm, 150 * mm, 50 * mm, 30 * mm, fill=1, stroke=1)
    c.setFillColor(black)
    c.drawString(25 * mm, 160 * mm, "Label 3")
    
    c.setStrokeColor(red)
    c.setFillColor(blue)
    c.rect(80 * mm, 150 * mm, 50 * mm, 30 * mm, fill=1, stroke=1)
    c.setFillColor(black)
    c.drawString(85 * mm, 160 * mm, "Label 4")
    
    # Add some info text
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, 100 * mm, "This is a demo PDF generated by Python AI Service")
    c.drawString(20 * mm, 90 * mm, f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(20 * mm, 80 * mm, "Status: PDF generation working correctly!")
    
    c.save()
    pdf_buffer.seek(0)
    return pdf_buffer.read()

def _is_truthy(val):
    """Check if form value is truthy (handles both string '1' and int 1 from json.loads)"""
    return str(val) == '1' or val is True

def generate_pdf_from_request(file, form_data):
    """Wrapper function to generate PDF from Flask request"""
    import tempfile
    import os
    
    # Save uploaded file temporarily with correct extension
    file_ext = os.path.splitext(file.filename)[1].lower() or '.pdf'
    with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as temp_file:
        file.save(temp_file.name)
        temp_path = temp_file.name
    
    try:
        # Extract parameters from form_data
        pages_meta = form_data.get('pagesData', [])
        if isinstance(pages_meta, str):
            try:
                pages_meta = json.loads(pages_meta)
            except:
                pages_meta = []
        
        # Get rotation from first page if available
        rotation = 0
        if pages_meta and len(pages_meta) > 0:
            rotation = pages_meta[0].get('rotation', 0)
            print(f"[DEBUG] Single file rotation: {rotation}°")
        
        plan_items = form_data.get('planData', [])  # ImpositionPage sends 'planData'
        if isinstance(plan_items, str):
            try:
                plan_items = json.loads(plan_items)
            except json.JSONDecodeError as e:
                print(f"[ERROR] Failed to parse planData JSON: {e}")
                plan_items = []
        
        # Debug logging
        print(f"[DEBUG] Received planData: {plan_items}")
        print(f"[DEBUG] Form data keys: {list(form_data.keys())}")
        
        page_w = float(form_data.get('pageW', 210))
        page_h = float(form_data.get('pageH', 297))
        item_w = float(form_data.get('itemW', 100))
        item_h = float(form_data.get('itemH', 50))
        dpi = int(form_data.get('dpi', 300))
        fit_mode = form_data.get('fitMode', 'fill')
        custom_scale = float(form_data.get('customScale', 100))
        background_color = form_data.get('backgroundColor', '#ffffff')
        color_mode = form_data.get('colorMode', 'original')
        gcr_level = float(form_data.get('gcrLevel', 100)) / 100.0  # Convert % → 0..1
        print(f"🔍 SERVER RECEIVED: fitMode={fit_mode}, customScale={custom_scale} (raw: {form_data.get('customScale')})", flush=True)
        use_crop = _is_truthy(form_data.get('useCrop', '0'))
        crop_len = float(form_data.get('cropLen', 10))
        crop_dist = float(form_data.get('cropDist', 10))
        crop_thick = float(form_data.get('cropThick', 0.5))
        crop_color = form_data.get('cropColor', '#000000')
        auto_rotate = _is_truthy(form_data.get('autoRotate', '0'))
        process_mode = form_data.get('processMode', 'vector')
        shape = form_data.get('shape', 'rect')
        
        # Advanced parameters
        use_page_crop = _is_truthy(form_data.get('usePageCrop', '0'))
        page_crop_len = float(form_data.get('pageCropLen', 10))
        page_crop_dist = float(form_data.get('pageCropDist', 10))
        page_crop_thick = float(form_data.get('pageCropThick', 0.5))
        page_crop_color = form_data.get('pageCropColor', '#000000')
        is_2sided = _is_truthy(form_data.get('is2Sided', '0'))
        rot_180_front = _is_truthy(form_data.get('rot180Front', '0'))
        rot_180_back = _is_truthy(form_data.get('rot180Back', '0'))
        data_mode = int(form_data.get('dataMode', 1))
        x_up_qty = int(form_data.get('xUpQty', 1))
        standard_qty = int(form_data.get('standardQty', 1))
        
        # If no plan_items provided, this is an error - don't create demo
        if not plan_items:
            print("[ERROR] No plan_items provided - this should not happen in normal operation")
            raise Exception("Không có dữ liệu layout (planData). Vui lòng thử lại.")
        
        print(f"[DEBUG] Generating PDF with {len(plan_items)} items, shape={shape}, fitMode={fit_mode}")
        print(f"[DEBUG] Page: {page_w}x{page_h}mm, Item: {item_w}x{item_h}mm, DPI: {dpi}")
        print(f"[DEBUG] First plan item: {plan_items[0] if plan_items else 'None'}")
        
        # Call the actual generate_pdf function
        pdf_bytes = generate_pdf(
            input_path=temp_path,
            plan_items=plan_items,
            page_w=page_w,
            page_h=page_h,
            item_w=item_w,
            item_h=item_h,
            dpi=dpi,
            fit_mode=fit_mode,
            custom_scale=custom_scale,
            background_color=background_color,            color_mode=color_mode,
            gcr_level=gcr_level,
            use_crop=use_crop,
            crop_len=crop_len,
            crop_dist=crop_dist,
            crop_thick=crop_thick,
            crop_color=crop_color,
            auto_rotate=auto_rotate,
            info_text='',
            process_mode=process_mode,
            shape=shape,
            rotation=rotation,  # Pass rotation from pagesData
            use_page_crop=use_page_crop,
            page_crop_len=page_crop_len,
            page_crop_dist=page_crop_dist,
            page_crop_thick=page_crop_thick,
            page_crop_color=page_crop_color,
            is_2sided=is_2sided,
            rot_180_front=rot_180_front,
            rot_180_back=rot_180_back,
            data_mode=data_mode,
            x_up_qty=x_up_qty,
            standard_qty=standard_qty
        )
        
        return pdf_bytes
        
    finally:
        # Clean up temporary file
        if os.path.exists(temp_path):
            os.unlink(temp_path)

def generate_pdf_multipage_from_request(files, form_data):
    """Wrapper function to generate multipage PDF from Flask request"""
    import tempfile
    import os
    
    temp_paths = []
    try:
        # Save uploaded files temporarily with correct extensions
        for file in files:
            # Get correct file extension
            file_ext = os.path.splitext(file.filename)[1].lower() or '.pdf'
            with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as temp_file:
                file.save(temp_file.name)
                temp_paths.append(temp_file.name)
        
        # Extract parameters from form_data
        pages_meta_str = form_data.get('pagesData', '[]')
        plan_items_str = form_data.get('planData', '[]')
        
        # Parse JSON strings
        try:
            pages_meta = json.loads(pages_meta_str) if isinstance(pages_meta_str, str) else pages_meta_str
            print(f"[DEBUG] pages_meta parsed: {pages_meta[:3] if len(pages_meta) > 0 else 'empty'}")
        except Exception as e:
            print(f"[ERROR] Failed to parse pagesData: {e}")
            pages_meta = []
        
        try:
            plan_items = json.loads(plan_items_str) if isinstance(plan_items_str, str) else plan_items_str
        except:
            plan_items = []
        # Extract all parameters for multipage PDF
        page_w = float(form_data.get('pageW', 210))
        page_h = float(form_data.get('pageH', 297))
        item_w = float(form_data.get('itemW', 100))
        item_h = float(form_data.get('itemH', 50))
        dpi = int(form_data.get('dpi', 300))
        fit_mode = form_data.get('fitMode', 'fill')
        custom_scale = float(form_data.get('customScale', 100))
        background_color = form_data.get('backgroundColor', '#ffffff')
        color_mode = form_data.get('colorMode', 'original')
        print(f"[DEBUG] MULTIPAGE - fitMode: {fit_mode}, customScale: {custom_scale}")
        use_crop = _is_truthy(form_data.get('useCrop', '0'))
        crop_len = float(form_data.get('cropLen', 10))
        crop_dist = float(form_data.get('cropDist', 10))
        crop_thick = float(form_data.get('cropThick', 0.5))
        crop_color = form_data.get('cropColor', '#000000')
        auto_rotate = _is_truthy(form_data.get('autoRotate', '0'))
        process_mode = form_data.get('processMode', 'vector')
        shape = form_data.get('shape', 'rect')
        
        # Advanced parameters
        use_page_crop = _is_truthy(form_data.get('usePageCrop', '0'))
        page_crop_len = float(form_data.get('pageCropLen', 10))
        page_crop_dist = float(form_data.get('pageCropDist', 10))
        page_crop_thick = float(form_data.get('pageCropThick', 0.5))
        page_crop_color = form_data.get('pageCropColor', '#000000')
        print(f"[DEBUG] CROP: useCrop={use_crop}, cropLen={crop_len}, usePageCrop={use_page_crop}, pageCropLen={page_crop_len}")
        is_2sided = _is_truthy(form_data.get('is2Sided', '0'))
        rot_180_front = _is_truthy(form_data.get('rot180Front', '0'))
        rot_180_back = _is_truthy(form_data.get('rot180Back', '0'))
        data_mode = int(form_data.get('dataMode', 1))
        x_up_qty = int(form_data.get('xUpQty', 1))
        standard_qty = int(form_data.get('standardQty', 1))
        total_sheets = int(form_data.get('totalSheets', 1))
        
        print(f"[DEBUG] Multipage PDF: {len(temp_paths)} files, {len(plan_items)} items, mode={data_mode}")
        
        # Call the actual generate_pdf_multipage function
        pdf_bytes = generate_pdf_multipage(
            input_paths=temp_paths,
            pages_meta=pages_meta,
            plan_items=plan_items,
            page_w=page_w,
            page_h=page_h,
            item_w=item_w,
            item_h=item_h,
            dpi=dpi,
            fit_mode=fit_mode,
            custom_scale=custom_scale,
            background_color=background_color,            color_mode=color_mode,
            use_crop=use_crop,
            crop_len=crop_len,
            crop_dist=crop_dist,
            crop_thick=crop_thick,
            crop_color=crop_color,
            auto_rotate=auto_rotate,
            info_text='',
            process_mode=process_mode,
            shape=shape,
            use_page_crop=use_page_crop,
            page_crop_len=page_crop_len,
            page_crop_dist=page_crop_dist,
            page_crop_thick=page_crop_thick,
            page_crop_color=page_crop_color,
            is_2sided=is_2sided,
            rot_180_front=rot_180_front,
            rot_180_back=rot_180_back,
            data_mode=data_mode,
            x_up_qty=x_up_qty,
            standard_qty=standard_qty,
            total_sheets=total_sheets
        )
        
        return pdf_bytes
        
    finally:
        # Clean up temporary files
        for temp_path in temp_paths:
            if os.path.exists(temp_path):
                os.unlink(temp_path)

@app.before_request
def before_request():
    """Initialize request context"""
    g.request_id = str(uuid.uuid4())
    g.start_time = time.time()
    print(f"[{g.request_id}] {request.method} {request.path}")

@app.after_request
def after_request(response):
    """Log request completion"""
    if hasattr(g, 'start_time'):
        duration = time.time() - g.start_time
        print(f"[{g.request_id}] Completed in {duration:.2f}s")
    return response

@app.errorhandler(413)
def handle_request_entity_too_large(e):
    return jsonify({
        'error': 'File too large',
        'message': 'File quá lớn. Tối đa 50MB.',
        'max_size_mb': 50
    }), 413

@app.errorhandler(Exception)
def handle_exception(e):
    """Global exception handler"""
    print(f"[ERROR] {str(e)}")
    return jsonify({
        'error': 'Internal server error',
        'message': 'Có lỗi xảy ra trên server',
        'details': str(e)
    }), 500

@app.route('/', methods=['GET'])
def root():
    """Root endpoint - redirect to health check"""
    return jsonify({
        'service': 'Python AI Service',
        'status': 'running',
        'port': 3005,
        'endpoints': {
            'health': '/health',
            'calculate': '/api/calculate',
            'generate_pdf': '/api/generate-pdf',
            'generate_svg': '/api/generate-svg',
            'preview': '/api/preview'
        },
        'docs': 'Truy cập /health để kiểm tra trạng thái service'
    })

@app.route('/api/inpaint/status', methods=['GET'])
def api_inpaint_status():
    """Check AI inpainting service status"""
    return jsonify({
        'available': AI_AVAILABLE,  # Basic AI with OpenCV inpainting
        'message': 'AI service sẵn sàng (OpenCV inpainting + Background removal)' if AI_AVAILABLE else 'AI service chưa được cài đặt',
        'models': {
            'rembg': AI_AVAILABLE,
            'torch': AI_AVAILABLE,
            'opencv_inpaint': AI_AVAILABLE,
            'lama': IOPAINT_AVAILABLE
        },
        'features': {
            'remove_bg': AI_AVAILABLE,
            'inpaint': AI_AVAILABLE,  # Now available with OpenCV
            'outpaint': IOPAINT_AVAILABLE
        },
        'requirements': [
            'torch>=2.0.0',
            'rembg>=2.0.0',
            'opencv-python>=4.8.0',
            'iopaint>=1.0.0 (optional for advanced inpainting)'
        ]
    })

@app.route('/api/remove-bg', methods=['POST'])
def api_remove_bg():
    """Remove background from image using rembg"""
    if not AI_AVAILABLE:
        return jsonify({
            'error': 'AI not available',
            'message': 'Chức năng AI chưa được cài đặt. Vui lòng cài đặt rembg và torch.'
        }), 501
    
    try:
        # Get uploaded file
        if 'file' not in request.files:
            return jsonify({'error': 'No file uploaded'}), 400
        
        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        # Read image
        input_image = Image.open(file.stream)
        
        # Remove background
        output_image = remove(input_image)
        
        # Convert to bytes
        img_io = io.BytesIO()
        output_image.save(img_io, 'PNG')
        img_io.seek(0)
        
        return Response(
            img_io.getvalue(),
            mimetype='image/png',
            headers={
                'Content-Disposition': 'attachment; filename=no_bg.png'
            }
        )
        
    except Exception as e:
        print(f"[ERROR] Background removal failed: {str(e)}")
        return jsonify({
            'error': 'Background removal failed',
            'message': 'Không thể xóa nền ảnh',
            'details': str(e)
        }), 500

@app.route('/api/inpaint', methods=['POST'])
def api_inpaint():
    """AI inpainting endpoint with improved box handling"""
    if not AI_AVAILABLE:
        return jsonify({
            'error': 'AI not available',
            'message': 'Chức năng AI chưa được cài đặt. Vui lòng cài đặt torch và opencv.',
            'install_guide': 'pip install torch opencv-python'
        }), 501
    
    try:
        # Get uploaded files
        if 'file' not in request.files:
            return jsonify({'error': 'No image file uploaded'}), 400
        
        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        # Read image
        import cv2
        import numpy as np
        from PIL import Image
        
        # Convert uploaded file to PIL Image
        image = Image.open(file.stream).convert('RGB')
        image_array = np.array(image)
        
        # Get boxes data for mask creation - handle both formats
        boxes_data = request.form.get('boxes', '[]')
        try:
            boxes = json.loads(boxes_data)
        except:
            boxes = []
        
        print(f"[DEBUG] Received boxes data: {boxes}")
        
        # Create mask from boxes
        mask = np.zeros(image_array.shape[:2], dtype=np.uint8)
        
        if not boxes:
            # Create a small test mask in the center for demo
            h, w = image_array.shape[:2]
            mask[h//4:3*h//4, w//4:3*w//4] = 255
            print(f"[DEBUG] No boxes provided, created test mask")
        else:
            # Handle different box formats
            for i, box in enumerate(boxes):
                try:
                    # Frontend sends boxes as objects with x, y, width, height
                    if isinstance(box, dict):
                        x = int(float(box.get('x', 0)))
                        y = int(float(box.get('y', 0)))
                        w = int(float(box.get('width', 50)))
                        h = int(float(box.get('height', 50)))
                    # Handle array format [x1, y1, x2, y2]
                    elif isinstance(box, (list, tuple)) and len(box) >= 4:
                        x1, y1, x2, y2 = box[:4]
                        x = int(float(x1))
                        y = int(float(y1))
                        w = int(float(x2)) - x
                        h = int(float(y2)) - y
                    else:
                        print(f"[WARNING] Invalid box format: {box}")
                        continue
                    
                    # Ensure coordinates are within image bounds
                    img_h, img_w = image_array.shape[:2]
                    x = max(0, min(x, img_w - 1))
                    y = max(0, min(y, img_h - 1))
                    w = max(1, min(w, img_w - x))
                    h = max(1, min(h, img_h - y))
                    
                    # Add to mask
                    mask[y:y+h, x:x+w] = 255
                    print(f"[DEBUG] Added box {i}: x={x}, y={y}, w={w}, h={h}")
                    
                except (ValueError, KeyError, TypeError) as e:
                    print(f"[WARNING] Invalid box data: {box}, error: {e}")
                    continue
        
        # Check if mask has any content
        if np.sum(mask) == 0:
            return jsonify({
                'error': 'No valid mask created',
                'message': 'Không thể tạo mask từ dữ liệu boxes'
            }), 400
        
        print(f"[DEBUG] Created mask with {np.sum(mask > 0)} pixels")
        
        # Simple inpainting using OpenCV
        result = cv2.inpaint(image_array, mask, 3, cv2.INPAINT_TELEA)
        
        # Convert back to PIL Image
        result_image = Image.fromarray(result)
        
        # Convert to bytes
        img_io = io.BytesIO()
        result_image.save(img_io, 'JPEG', quality=95)
        img_io.seek(0)
        
        return Response(
            img_io.getvalue(),
            mimetype='image/jpeg',
            headers={
                'Content-Disposition': 'attachment; filename=inpainted.jpg'
            }
        )
        
    except Exception as e:
        print(f"[ERROR] AI inpainting failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'error': 'AI inpainting failed',
            'message': 'Không thể thực hiện AI inpainting',
            'details': str(e)
        }), 500

@app.route('/api/outpaint', methods=['POST'])
def api_outpaint():
    """AI outpainting endpoint - Expand images with white background"""
    try:
        # Get uploaded file
        if 'file' not in request.files:
            return jsonify({'error': 'No image file uploaded'}), 400
        
        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        # Get expansion parameters (in mm)
        top_mm = float(request.form.get('top_mm', 0))
        bottom_mm = float(request.form.get('bottom_mm', 0))
        left_mm = float(request.form.get('left_mm', 0))
        right_mm = float(request.form.get('right_mm', 0))
        dpi = int(request.form.get('dpi', 300))
        process_mode = request.form.get('process_mode', 'raster')
        
        print(f"[OUTPAINT] Expanding: top={top_mm}, bottom={bottom_mm}, left={left_mm}, right={right_mm}mm at {dpi}DPI")
        
        # Convert mm to pixels
        def mm_to_px(mm_val):
            return int((mm_val / 25.4) * dpi)
        
        top_px = mm_to_px(top_mm)
        bottom_px = mm_to_px(bottom_mm)
        left_px = mm_to_px(left_mm)
        right_px = mm_to_px(right_mm)
        
        # Load image
        from PIL import Image
        import io
        import base64
        
        # Detect file type and load appropriately
        file_ext = os.path.splitext(file.filename)[1].lower()
        
        if file_ext == '.pdf':
            # Handle PDF
            import tempfile
            with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as temp_file:
                file.save(temp_file.name)
                temp_path = temp_file.name
            
            try:
                # Load PDF page as image
                doc = fitz.open(temp_path)
                page = doc.load_page(0)
                pix = page.get_pixmap(dpi=dpi, alpha=False)
                img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                doc.close()
            finally:
                if os.path.exists(temp_path):
                    os.unlink(temp_path)
        else:
            # Handle image files
            img = Image.open(file.stream)
            if img.mode == 'RGBA':
                # Flatten alpha to white background
                bg = Image.new('RGB', img.size, (255, 255, 255))
                bg.paste(img, mask=img.split()[3])
                img = bg
            elif img.mode != 'RGB':
                img = img.convert('RGB')
        
        # Get original dimensions
        orig_w, orig_h = img.size
        
        # Calculate new dimensions
        new_w = orig_w + left_px + right_px
        new_h = orig_h + top_px + bottom_px
        
        # Run AI Outpainting using LaMa CPU model
        try:
            from bleed_outpainter import get_bleed_outpainter
            print(f"[OUTPAINT] Running LaMa CPU Outpainter: {orig_w}x{orig_h} -> {new_w}x{new_h} (T={top_px}, R={right_px}, B={bottom_px}, L={left_px})")
            outpainter = get_bleed_outpainter()
            expanded = outpainter.outpaint(
                img,
                pad_pixels=(top_px, right_px, bottom_px, left_px),
                pre_fill_method="smart_portrait",
                feather_edge=3,
                preserve_center=True
            )
        except Exception as ai_err:
            print(f"[OUTPAINT] Warning: LaMa AI inference failed ({ai_err}), falling back to border padding")
            expanded = Image.new('RGB', (new_w, new_h), (255, 255, 255))
            expanded.paste(img, (left_px, top_px))
        
        # Convert back to base64
        img_buffer = io.BytesIO()
        expanded.save(img_buffer, format='JPEG', quality=95)
        img_buffer.seek(0)
        img_base64 = base64.b64encode(img_buffer.read()).decode('utf-8')
        
        # Calculate new dimensions in mm
        new_w_mm = (new_w / dpi) * 25.4
        new_h_mm = (new_h / dpi) * 25.4
        
        print(f"[OUTPAINT] Success: {orig_w}x{orig_h}px -> {new_w}x{new_h}px ({new_w_mm:.1f}x{new_h_mm:.1f}mm)")
        
        return jsonify({
            'success': True,
            'message': 'Mở rộng ảnh thành công',
            'image': f'data:image/jpeg;base64,{img_base64}',
            'width_mm': round(new_w_mm, 1),
            'height_mm': round(new_h_mm, 1),
            'original_size': f'{orig_w}x{orig_h}px',
            'new_size': f'{new_w}x{new_h}px'
        })
        
    except Exception as e:
        print(f"[ERROR] AI outpainting failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'error': 'AI outpainting failed',
            'message': 'Không thể thực hiện mở rộng ảnh',
            'details': str(e)
        }), 500

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'service': 'Python AI Service',
        'port': 3005,
        'timestamp': datetime.now().isoformat(),
        'uptime': time.time() - app.config.get('start_time', time.time())
    })

@app.route('/api/health', methods=['GET'])
def api_health_check():
    """API Health check endpoint (alias for /health)"""
    return health_check()

@app.route('/api/python-health', methods=['GET'])
def python_health_check():
    """Python-specific health check endpoint for frontend"""
    return health_check()

@app.route('/api/icc-profiles', methods=['GET'])
def get_icc_profiles():
    """Get list of available ICC profiles from iccpro directory"""
    try:
        icc_dir = os.path.join(os.path.dirname(__file__), 'icc', 'iccpro')
        if not os.path.exists(icc_dir):
            return jsonify({'error': 'ICC profiles directory not found'}), 404
        
        profiles = []
        for filename in os.listdir(icc_dir):
            if filename.lower().endswith('.icc'):
                # Remove .icc extension for display name
                display_name = filename[:-4]
                profiles.append({
                    'filename': filename,
                    'name': display_name,
                    'path': os.path.join(icc_dir, filename)
                })
        
        # Sort profiles alphabetically
        profiles.sort(key=lambda x: x['name'])
        
        return jsonify({
            'profiles': profiles,
            'count': len(profiles)
        })
    except Exception as e:
        logger.error(f"Error getting ICC profiles: {str(e)}")
        return jsonify({'error': str(e)}), 500

def apply_advanced_color_management(image, form_data):
    """Apply 3-layer ICC color management to image"""
    try:
        # Check if advanced color management is enabled
        use_advanced_color = form_data.get('useAdvancedColor') == '1'
        if not use_advanced_color:
            return image
        
        source_icc = form_data.get('sourceIcc', 'original')
        icc1 = form_data.get('icc1', '')
        icc_output = form_data.get('iccOutput', '')
        
        logger.info(f"Advanced color management: source={source_icc}, icc1={icc1}, output={icc_output}")
        
        # Import PIL for color management
        from PIL import Image as PILImage, ImageCms
        
        # Convert to PIL Image if needed
        if hasattr(image, 'mode'):
            pil_image = image
        else:
            # Convert from other formats if needed
            pil_image = image
        
        icc_dir = os.path.join(os.path.dirname(__file__), 'icc', 'iccpro')
        
        # Layer 1: Source ICC conversion
        if source_icc != 'original' and source_icc:
            source_profile_path = os.path.join(icc_dir, source_icc)
            if os.path.exists(source_profile_path):
                try:
                    source_profile = ImageCms.ImageCmsProfile(source_profile_path)
                    # Convert from source profile to working space (sRGB)
                    srgb_profile = ImageCms.createProfile('sRGB')
                    transform = ImageCms.buildTransformFromOpenProfiles(
                        source_profile, srgb_profile, 'RGB', 'RGB'
                    )
                    pil_image = ImageCms.applyTransform(pil_image.convert('RGB'), transform)
                    logger.info(f"Applied source ICC: {source_icc}")
                except Exception as e:
                    logger.warning(f"Failed to apply source ICC {source_icc}: {e}")
        
        # Layer 2: First ICC conversion
        if icc1:
            icc1_profile_path = os.path.join(icc_dir, icc1)
            if os.path.exists(icc1_profile_path):
                try:
                    icc1_profile = ImageCms.ImageCmsProfile(icc1_profile_path)
                    srgb_profile = ImageCms.createProfile('sRGB')
                    transform = ImageCms.buildTransformFromOpenProfiles(
                        srgb_profile, icc1_profile, 'RGB', 'RGB'
                    )
                    pil_image = ImageCms.applyTransform(pil_image.convert('RGB'), transform)
                    logger.info(f"Applied ICC layer 1: {icc1}")
                except Exception as e:
                    logger.warning(f"Failed to apply ICC1 {icc1}: {e}")
        
        # Layer 3: Output ICC conversion (final)
        if icc_output:
            output_profile_path = os.path.join(icc_dir, icc_output)
            if os.path.exists(output_profile_path):
                try:
                    output_profile = ImageCms.ImageCmsProfile(output_profile_path)
                    # Convert from current space to output profile
                    current_profile = ImageCms.createProfile('sRGB')  # Assume sRGB working space
                    transform = ImageCms.buildTransformFromOpenProfiles(
                        current_profile, output_profile, 'RGB', 'RGB'
                    )
                    pil_image = ImageCms.applyTransform(pil_image.convert('RGB'), transform)
                    logger.info(f"Applied output ICC: {icc_output}")
                except Exception as e:
                    logger.warning(f"Failed to apply output ICC {icc_output}: {e}")
        
        return pil_image
        
    except Exception as e:
        logger.error(f"Error in advanced color management: {e}")
        return image  # Return original image if color management fails

# ============================================================
# Source file storage - upload once, reuse for PDF generation
# ============================================================
source_files = {}  # file_id -> { path, filename, uploaded_at }

SOURCE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'source_files')
os.makedirs(SOURCE_DIR, exist_ok=True)

@app.route('/api/upload-source', methods=['POST'])
def api_upload_source():
    """Upload source file, save original, return file_id + thumbnail"""
    try:
        if 'file' not in request.files:
            return jsonify({'error': 'No file provided'}), 400
        
        file = request.files['file']
        if not file.filename:
            return jsonify({'error': 'Empty filename'}), 400
        
        file_id = str(uuid.uuid4())
        ext = os.path.splitext(file.filename)[1].lower() or '.png'
        save_path = os.path.join(SOURCE_DIR, f'{file_id}{ext}')
        file.save(save_path)
        
        source_files[file_id] = {
            'path': save_path,
            'filename': file.filename,
            'uploaded_at': datetime.now().isoformat()
        }
        
        # Generate thumbnail from original file
        thumb_b64, w_mm, h_mm = _make_thumbnail(save_path, ext)
        
        print(f"[UPLOAD] {file.filename} -> {file_id} ({os.path.getsize(save_path)} bytes)")
        
        return jsonify({
            'file_id': file_id,
            'filename': file.filename,
            'thumb': thumb_b64,
            'w_mm': w_mm,
            'h_mm': h_mm
        })
    except Exception as e:
        print(f"[ERROR] upload-source: {e}")
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500


@app.route('/api/upload-source-batch', methods=['POST'])
def api_upload_source_batch():
    """Upload multiple source files at once, extract all pages from PDFs"""
    try:
        files = request.files.getlist('files')
        if not files:
            return jsonify({'error': 'No files provided'}), 400
        
        skip_thumbnails = request.form.get('skip_thumbnails') == '1'
        results = []
        for file in files:
            if not file.filename:
                continue
            
            file_id = str(uuid.uuid4())
            ext = os.path.splitext(file.filename)[1].lower() or '.png'
            save_path = os.path.join(SOURCE_DIR, f'{file_id}{ext}')
            file.save(save_path)
            
            source_files[file_id] = {
                'path': save_path,
                'filename': file.filename,
                'uploaded_at': datetime.now().isoformat()
            }
            
            if ext == '.pdf':
                import fitz
                doc = fitz.open(save_path)
                num_pages = len(doc)
                if skip_thumbnails:
                    # Fast mode: only read metadata, no thumbnail rendering
                    page = doc[0]
                    rect = page.rect
                    w_mm = round(rect.width * 0.352778, 1)
                    h_mm = round(rect.height * 0.352778, 1)
                    doc.close()
                    for page_idx in range(num_pages):
                        page_label = f"{file.filename} (trang {page_idx + 1}/{num_pages})" if num_pages > 1 else file.filename
                        results.append({
                            'file_id': file_id,
                            'filename': page_label,
                            'thumb': '',
                            'w_mm': w_mm,
                            'h_mm': h_mm,
                            'page': page_idx + 1,
                            'total_pages': num_pages
                        })
                else:
                    # Normal mode: render thumbnails
                    from PIL import Image
                    from io import BytesIO
                    for page_idx in range(num_pages):
                        page = doc[page_idx]
                        pix = page.get_pixmap(dpi=72, alpha=False)
                        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                        rect = page.rect
                        w_mm = round(rect.width * 0.352778, 1)
                        h_mm = round(rect.height * 0.352778, 1)
                        img.thumbnail((200, 200), Image.Resampling.LANCZOS)
                        buf = BytesIO()
                        img.save(buf, format='JPEG', quality=70)
                        buf.seek(0)
                        thumb_b64 = f"data:image/jpeg;base64,{base64.b64encode(buf.read()).decode()}"
                        page_label = f"{file.filename} (trang {page_idx + 1}/{num_pages})" if num_pages > 1 else file.filename
                        results.append({
                            'file_id': file_id,
                            'filename': page_label,
                            'thumb': thumb_b64,
                            'w_mm': w_mm,
                            'h_mm': h_mm,
                            'page': page_idx + 1,
                            'total_pages': num_pages
                        })
                    doc.close()
                print(f"[UPLOAD] {file.filename} -> {file_id} ({num_pages} pages, skip_thumb={skip_thumbnails})")
            else:
                thumb_b64, w_mm, h_mm = _make_thumbnail(save_path, ext)
                print(f"[UPLOAD] {file.filename} -> {file_id} ({os.path.getsize(save_path)} bytes)")
                results.append({
                    'file_id': file_id,
                    'filename': file.filename,
                    'thumb': thumb_b64,
                    'w_mm': w_mm,
                    'h_mm': h_mm,
                    'page': 1,
                    'total_pages': 1
                })
        
        return jsonify({'files': results})
    except Exception as e:
        print(f"[ERROR] upload-source-batch: {e}")
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500


@app.route('/api/delete-source/<file_id>', methods=['DELETE'])
def api_delete_source(file_id):
    """Delete a source file"""
    try:
        info = source_files.pop(file_id, None)
        if info and os.path.exists(info['path']):
            os.unlink(info['path'])
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


def _make_thumbnail_page(file_path, page_idx, max_size=400):
    """Generate thumbnail + dimensions for a specific PDF page"""
    from PIL import Image
    from io import BytesIO
    import fitz
    
    doc = fitz.open(file_path)
    page = doc[page_idx]
    pix = page.get_pixmap(dpi=72, alpha=False)
    img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
    rect = page.rect
    w_mm = round(rect.width * 0.352778, 1)
    h_mm = round(rect.height * 0.352778, 1)
    doc.close()
    
    img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)
    buf = BytesIO()
    img.save(buf, format='JPEG', quality=90)
    buf.seek(0)
    thumb_b64 = f"data:image/jpeg;base64,{base64.b64encode(buf.read()).decode()}"
    return thumb_b64, w_mm, h_mm


def _make_thumbnail(file_path, ext, max_size=400):
    """Generate thumbnail + dimensions in mm from source file"""
    from PIL import Image, ImageOps
    from io import BytesIO
    import fitz
    
    if ext == '.pdf':
        doc = fitz.open(file_path)
        page = doc[0]
        pix = page.get_pixmap(dpi=150, alpha=False)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        # PDF dimensions from mediabox (points -> mm)
        rect = page.rect
        w_mm = round(rect.width * 0.352778, 1)
        h_mm = round(rect.height * 0.352778, 1)
        doc.close()
    else:
        img = Image.open(file_path)
        img = ImageOps.exif_transpose(img)
        if img.mode == 'RGBA':
            bg = Image.new('RGB', img.size, (255, 255, 255))
            bg.paste(img, mask=img.split()[3])
            img = bg
        elif img.mode not in ('RGB',):
            img = img.convert('RGB')
        # Assume 300 DPI for images
        w_mm = round(img.width / 300 * 25.4, 1)
        h_mm = round(img.height / 300 * 25.4, 1)
    
    # Resize for thumbnail
    img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)
    
    buf = BytesIO()
    img.save(buf, format='JPEG', quality=90)
    buf.seek(0)
    thumb_b64 = f"data:image/jpeg;base64,{base64.b64encode(buf.read()).decode()}"
    
    return thumb_b64, w_mm, h_mm


@app.route('/api/nest-svg', methods=['POST'])
def api_nest_svg():
    """Nest SVG die-cut shapes on a sheet using true contour"""
    try:
        from nesting import parse_svg_to_polygon, nest_on_sheet
        
        svg_text = request.form.get('svgData', '')
        sheet_w = float(request.form.get('sheetW', 320))
        sheet_h = float(request.form.get('sheetH', 430))
        item_w = float(request.form.get('itemW', 30))
        item_h = float(request.form.get('itemH', 78))
        padding = float(request.form.get('padding', 0))
        rotations_str = request.form.get('rotations', '0,45,90,135,180')
        rotations = [float(r) for r in rotations_str.split(',')]
        
        if not svg_text:
            return jsonify({'error': 'No SVG data'}), 400
        
        poly, vb_w, vb_h = parse_svg_to_polygon(svg_text)
        if poly is None:
            return jsonify({'error': 'Failed to parse SVG'}), 400
        
        results = nest_on_sheet(poly, sheet_w, sheet_h, item_w, item_h, padding, rotations)
        
        return jsonify({
            'success': True,
            'results': results[:10],  # Top 10 plans
            'svgBounds': {'w': vb_w, 'h': vb_h}
        })
    except Exception as e:
        print(f"[NEST] Error: {e}")
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/api/calculate', methods=['POST'])
def api_calculate():
    """Calculate layout plans"""
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No JSON data provided'}), 400
        
        # Validate required fields
        required_fields = ['shape', 'itemW', 'itemH', 'padding', 'printW', 'printH', 'pageW', 'pageH']
        for field in required_fields:
            if field not in data:
                return jsonify({'error': f'Missing required field: {field}'}), 400
        
        # Calculate layout
        result = calculate_layout(
            shape=data['shape'],
            item_w=data['itemW'],
            item_h=data['itemH'],
            padding=data['padding'],
            print_w=data['printW'],
            print_h=data['printH'],
            page_w=data['pageW'],
            page_h=data['pageH']
        )
        
        return jsonify({
            'success': True,
            'data': result,
            'request_id': g.request_id
        })
        
    except Exception as e:
        print(f"[ERROR] Layout calculation failed: {str(e)}")
        return jsonify({
            'error': 'Layout calculation failed',
            'message': 'Không thể tính toán layout',
            'details': str(e)
        }), 500

@app.route('/api/generate-pdf-async', methods=['POST'])
def api_generate_pdf_async():
    """Generate PDF asynchronously - returns task ID"""
    try:
        task_id = str(uuid.uuid4())
        
        # Initialize tasks storage
        if not hasattr(app, 'tasks'):
            app.tasks = {}
        
        # Capture request data before starting thread
        files_data = []
        source_paths = []  # New: paths from source_files storage
        
        # Check for file_ids first (new flow: files already uploaded via upload-source)
        file_ids_raw = request.form.get('fileIds', None)
        if file_ids_raw:
            try:
                file_ids = json.loads(file_ids_raw) if isinstance(file_ids_raw, str) else file_ids_raw
            except:
                file_ids = []
            for fid in file_ids:
                info = source_files.get(fid)
                if info and os.path.exists(info['path']):
                    source_paths.append({'path': info['path'], 'filename': info['filename']})
                else:
                    print(f"[WARN] file_id not found: {fid}")
        
        # Fallback: accept uploaded files directly (backward compatible)
        if not source_paths:
            if 'file' in request.files:
                file = request.files['file']
                files_data.append({
                    'filename': file.filename or 'uploaded_file.pdf',
                    'content': file.read()
                })
            elif 'files' in request.files:
                for file in request.files.getlist('files'):
                    files_data.append({
                        'filename': file.filename or f'uploaded_file_{len(files_data)}.pdf',
                        'content': file.read()
                    })
        
        form_data = {}
        for key in request.form:
            try:
                # Try to parse as JSON first
                form_data[key] = json.loads(request.form[key])
            except (json.JSONDecodeError, ValueError):
                # If JSON parsing fails, use raw string
                form_data[key] = request.form[key]
        
        # Debug logging
        print(f"[DEBUG] Async PDF - Form data keys: {list(form_data.keys())}")
        if 'pagesData' in form_data:
            print(f"[DEBUG] Async PDF - pagesData: {form_data['pagesData'][:3] if isinstance(form_data['pagesData'], list) and len(form_data['pagesData']) > 0 else form_data['pagesData']}")
        if 'planData' in form_data:
            print(f"[DEBUG] Async PDF - planData type: {type(form_data['planData'])}, length: {len(form_data['planData']) if isinstance(form_data['planData'], (list, str)) else 'N/A'}")
        else:
            print("[ERROR] Async PDF - No planData in form_data!")
        
        # Create task with proper structure matching Frontend expectations
        current_time = datetime.now().isoformat()
        app.tasks[task_id] = {
            'id': task_id,
            'task_type': 'pdf_generation',
            'status': 'pending',
            'progress': 0,
            'message': 'Đang khởi tạo task...',
            'error': None,
            'result': None,
            'created_at': current_time,
            'started_at': None,
            'completed_at': None,
            'pdf_data': None,
            'files_data': files_data,
            'source_paths': source_paths,
            'form_data': form_data
        }
        
        # Start processing in background
        def process_pdf():
            try:
                # Update status to running
                app.tasks[task_id]['status'] = 'running'
                app.tasks[task_id]['started_at'] = datetime.now().isoformat()
                app.tasks[task_id]['message'] = 'Đang xử lý PDF...'
                app.tasks[task_id]['progress'] = 10
                
                # Get captured data
                files_data = app.tasks[task_id]['files_data']
                form_data = app.tasks[task_id]['form_data']
                
                app.tasks[task_id]['progress'] = 30
                app.tasks[task_id]['message'] = 'Đang tạo PDF...'
                
                # Generate actual PDF
                source_paths = app.tasks[task_id].get('source_paths', [])
                
                try:
                    if source_paths:
                        # New flow: use pre-uploaded source files (no temp files needed)
                        mock_files = [MockFile(sp['path'], sp['filename']) for sp in source_paths]
                        if len(mock_files) == 1:
                            pdf_bytes = generate_pdf_from_request(mock_files[0], form_data)
                        else:
                            pdf_bytes = generate_pdf_multipage_from_request(mock_files, form_data)
                    elif files_data:
                        # Legacy flow: files uploaded inline
                        import tempfile
                        temp_files = []
                        try:
                            for file_data in files_data:
                                filename = file_data.get('filename', 'file.pdf')
                                file_ext = os.path.splitext(filename)[1].lower() or '.pdf'
                                with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as tf:
                                    tf.write(file_data['content'])
                                    temp_files.append(tf.name)
                            
                            if len(temp_files) == 1:
                                mock_file = MockFile(temp_files[0], files_data[0]['filename'])
                                pdf_bytes = generate_pdf_from_request(mock_file, form_data)
                            else:
                                mock_files = [MockFile(path, files_data[i]['filename']) for i, path in enumerate(temp_files)]
                                pdf_bytes = generate_pdf_multipage_from_request(mock_files, form_data)
                        finally:
                            for tf in temp_files:
                                if os.path.exists(tf):
                                    os.unlink(tf)
                    else:
                        app.tasks[task_id]['status'] = 'failed'
                        app.tasks[task_id]['error'] = 'Không có file được upload'
                        app.tasks[task_id]['message'] = 'Lỗi: Không có file được upload'
                        app.tasks[task_id]['completed_at'] = datetime.now().isoformat()
                        return
                except Exception as e:
                    print(f"[ERROR] PDF generation failed: {str(e)}")
                    import traceback
                    traceback.print_exc()
                    app.tasks[task_id]['status'] = 'failed'
                    app.tasks[task_id]['error'] = f'Lỗi tạo PDF: {str(e)}'
                    app.tasks[task_id]['message'] = f'Lỗi: {str(e)}'
                    app.tasks[task_id]['completed_at'] = datetime.now().isoformat()
                    return
                
                app.tasks[task_id]['progress'] = 90
                app.tasks[task_id]['message'] = 'Hoàn tất xử lý...'
                
                # Store result with proper structure
                app.tasks[task_id]['status'] = 'success'
                app.tasks[task_id]['progress'] = 100
                app.tasks[task_id]['message'] = 'Hoàn thành!'
                app.tasks[task_id]['completed_at'] = datetime.now().isoformat()
                app.tasks[task_id]['pdf_data'] = pdf_bytes
                app.tasks[task_id]['result'] = {
                    'file_path': f'/api/task/{task_id}/download',
                    'file_name': 'generated.pdf',
                    'file_size': len(pdf_bytes),
                    'total_sheets': 1
                }
                
            except Exception as e:
                print(f"[ERROR] Background PDF processing failed: {str(e)}")
                import traceback
                traceback.print_exc()
                app.tasks[task_id]['status'] = 'failed'
                app.tasks[task_id]['error'] = str(e)
                app.tasks[task_id]['message'] = f'Lỗi: {str(e)}'
                app.tasks[task_id]['completed_at'] = datetime.now().isoformat()
        
        # Start background thread
        thread = threading.Thread(target=process_pdf)
        thread.daemon = True
        thread.start()
        
        # Return task ID immediately
        return jsonify({'task_id': task_id})
        
    except Exception as e:
        print(f"[ERROR] PDF async generation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'error': 'PDF generation failed',
            'message': 'Không thể tạo PDF',
            'details': str(e)
        }), 500

@app.route('/api/task/<task_id>', methods=['GET'])
def api_task_status(task_id):
    """Get task status with proper structure matching Frontend expectations"""
    try:
        if not hasattr(app, 'tasks') or task_id not in app.tasks:
            return jsonify({'error': 'Task not found'}), 404
        
        task = app.tasks[task_id]
        
        # Return task status with exact structure Frontend expects
        return jsonify({
            'id': task['id'],
            'task_type': task['task_type'],
            'status': task['status'],
            'progress': task['progress'],
            'message': task['message'],
            'result': task.get('result'),  # This should be the nested object with file_path, etc.
            'error': task.get('error'),
            'created_at': task.get('created_at'),
            'started_at': task.get('started_at'),
            'completed_at': task.get('completed_at')
        })
        
    except Exception as e:
        print(f"[ERROR] Task status check failed: {str(e)}")
        return jsonify({
            'error': 'Task status check failed',
            'details': str(e)
        }), 500

@app.route('/api/task/<task_id>/download', methods=['GET'])
def api_task_download(task_id):
    """Download task result"""
    try:
        if not hasattr(app, 'tasks') or task_id not in app.tasks:
            return jsonify({'error': 'Task not found'}), 404
        
        task = app.tasks[task_id]
        
        if task['status'] != 'success' or not task.get('pdf_data'):
            return jsonify({'error': 'Task not completed or no result available'}), 400
        
        # Return PDF from stored data
        pdf_data = task['pdf_data']
        return Response(
            pdf_data,
            mimetype='application/pdf',
            headers={
                'Content-Disposition': 'attachment; filename=generated.pdf',
                'Content-Length': len(pdf_data)
            }
        )
        
    except Exception as e:
        print(f"[ERROR] Task download failed: {str(e)}")
        return jsonify({
            'error': 'Task download failed',
            'details': str(e)
        }), 500

@app.route('/api/generate-pdf', methods=['POST'])
def api_generate_pdf():
    """Generate PDF"""
    try:
        # Handle file uploads
        files = []
        if 'file' in request.files:
            files = [request.files['file']]
        elif 'files' in request.files:
            files = request.files.getlist('files')
        
        # Validate files
        for file in files:
            if not file or file.filename == '':
                return jsonify({'error': 'No file selected'}), 400
            
            # Check file size (basic validation)
            file.seek(0, 2)  # Seek to end
            size = file.tell()
            file.seek(0)  # Reset to beginning
            
            if size > 50 * 1024 * 1024:  # 50MB
                return jsonify({
                    'error': 'File too large',
                    'message': f'File {file.filename} quá lớn. Tối đa 50MB.'
                }), 413
        
        # Get form data
        form_data = {}
        for key in request.form:
            try:
                form_data[key] = json.loads(request.form[key])
            except:
                form_data[key] = request.form[key]
        
        # Generate PDF
        if len(files) == 1:
            pdf_bytes = generate_pdf_from_request(files[0], form_data)
        else:
            pdf_bytes = generate_pdf_multipage_from_request(files, form_data)
        
        # Return PDF
        return Response(
            pdf_bytes,
            mimetype='application/pdf',
            headers={
                'Content-Disposition': 'attachment; filename=print_layout.pdf',
                'Content-Length': len(pdf_bytes)
            }
        )
        
    except Exception as e:
        print(f"[ERROR] PDF generation failed: {str(e)}")
        return jsonify({
            'error': 'PDF generation failed',
            'message': 'Không thể tạo PDF',
            'details': str(e)
        }), 500

@app.route('/api/generate-svg', methods=['POST'])
def api_generate_svg():
    """Generate SVG cut file"""
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No JSON data provided'}), 400
        
        svg_content = generate_svg(data)
        
        return Response(
            svg_content,
            mimetype='image/svg+xml',
            headers={
                'Content-Disposition': 'attachment; filename=cut_layout.svg'
            }
        )
        
    except Exception as e:
        print(f"[ERROR] SVG generation failed: {str(e)}")
        return jsonify({
            'error': 'SVG generation failed',
            'message': 'Không thể tạo SVG',
            'details': str(e)
        }), 500

@app.route('/api/render-preview', methods=['POST'])
def api_render_preview():
    """Render preview thumbnail for imposition with proper implementation"""
    try:
        # Handle file uploads
        files = []
        if 'file' in request.files:
            files = [request.files['file']]
        elif 'files' in request.files:
            files = request.files.getlist('files')
        
        if not files or not files[0]:
            return jsonify({'error': 'No file uploaded'}), 400
        
        # Get form data
        form_data = {}
        for key in request.form:
            try:
                form_data[key] = json.loads(request.form[key])
            except:
                form_data[key] = request.form[key]
        
        # Extract parameters
        item_w = float(form_data.get('itemW', 100))
        item_h = float(form_data.get('itemH', 100))
        fit_mode = form_data.get('fitMode', 'stretch')
        shape = form_data.get('shape', 'rect')
        manual_rotate = form_data.get('manualRotate', 'auto')
        
        print(f"[DEBUG] Preview params: itemW={item_w}, itemH={item_h}, fitMode={fit_mode}, shape={shape}, rotate={manual_rotate}")
        
        # Save uploaded file temporarily with correct extension
        import tempfile
        file_ext = os.path.splitext(files[0].filename)[1].lower() or '.pdf'
        with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as temp_file:
            files[0].save(temp_file.name)
            temp_path = temp_file.name
        
        try:
            # Use the existing render_preview_thumbnail function
            result = render_preview_thumbnail(
                input_path=temp_path,
                item_w=item_w,
                item_h=item_h,
                fit_mode=fit_mode,
                shape=shape,
                manual_rotate=manual_rotate,
                form_data=form_data  # Pass form_data for advanced color management
            )
            
            return jsonify({
                'success': True,
                'message': 'Preview rendered successfully',
                'portrait': result['portrait'],
                'landscape': result['landscape'],
                'rotated': result.get('rotated', False)
            })
            
        finally:
            # Clean up temporary file
            if os.path.exists(temp_path):
                os.unlink(temp_path)
        
    except Exception as e:
        print(f"[ERROR] Preview rendering failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'error': 'Preview rendering failed',
            'message': 'Không thể tạo preview',
            'details': str(e)
        }), 500

@app.route('/api/render-sheet-preview', methods=['POST'])
def render_sheet_preview():
    """Render a single sheet preview as PNG image - same logic as PDF but outputs image"""
    try:
        from PIL import Image, ImageDraw
        
        form = request.form
        plan_items = json.loads(form.get('planData', '[]'))
        file_ids = json.loads(form.get('fileIds', '[]'))
        pages_meta = json.loads(form.get('pagesData', '[]'))
        
        page_w = float(form.get('pageW', 330))
        page_h = float(form.get('pageH', 480))
        item_w = float(form.get('itemW', 100))
        item_h = float(form.get('itemH', 120))
        fit_mode = form.get('fitMode', 'stretch')
        shape = form.get('shape', 'rect')
        auto_rotate = _is_truthy(form.get('autoRotate', '0'))
        sheet_index = int(form.get('sheetIndex', 0))
        data_mode = int(form.get('dataMode', 1))
        standard_qty = int(form.get('standardQty', 1))
        x_up_qty = int(form.get('xUpQty', 1))
        preview_dpi = int(form.get('previewDpi', 72))
        bg_color = form.get('backgroundColor', '#ffffff')
        
        # Convert mm to pixels
        scale = preview_dpi / 25.4
        pw = int(page_w * scale)
        ph = int(page_h * scale)
        
        # Parse bg color
        try:
            r, g, b = int(bg_color[1:3], 16), int(bg_color[3:5], 16), int(bg_color[5:7], 16)
        except:
            r, g, b = 255, 255, 255
        
        canvas = Image.new('RGB', (pw, ph), (r, g, b))
        
        # Load source images from file IDs
        source_images = []
        for fid in file_ids:
            if fid in source_files:
                path = source_files[fid]['path']
                ext = os.path.splitext(path)[1].lower()
                try:
                    if ext == '.pdf':
                        import fitz
                        doc = fitz.open(path)
                        page = doc[0]
                        pix = page.get_pixmap(dpi=preview_dpi, alpha=False)
                        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                        doc.close()
                    else:
                        img = Image.open(path).convert('RGB')
                    source_images.append(img)
                except Exception as e:
                    print(f"[PREVIEW] Failed to load {fid}: {e}")
                    source_images.append(None)
            else:
                source_images.append(None)
        
        # Get page for slot (same logic as PDF generation)
        def get_page_idx(slot_idx):
            n = len(source_images)
            if n == 0: return -1
            items_per_sheet = len(plan_items)
            if data_mode == 1:
                gi = sheet_index * items_per_sheet + slot_idx
                return (gi // standard_qty) % n
            elif data_mode == 4:
                return (sheet_index // x_up_qty) % n
            else:
                gi = sheet_index * items_per_sheet + slot_idx
                return gi % n
        
        is_flip_shape = shape in ('triangle', 'trapezoid', 'hexagon')
        effective_item_h = item_w if shape == 'circle' else item_h
        
        for slot_idx, item in enumerate(plan_items):
            page_idx = get_page_idx(slot_idx)
            if page_idx < 0 or page_idx >= len(source_images) or source_images[page_idx] is None:
                continue
            
            src = source_images[page_idx]
            
            # Calculate slot dimensions
            eff_item_h = item_w if shape == 'circle' else item_h
            if is_flip_shape:
                sw, sh = item_w, eff_item_h
            elif item.get('rot', False):
                sw, sh = eff_item_h, item_w
            else:
                sw, sh = item_w, eff_item_h
            if 'w' in item and item['w'] is not None:
                sw = float(item['w'])
            if 'h' in item and item['h'] is not None:
                sh = float(item['h'])
            if shape == 'circle':
                sh = sw
            
            tw = int(sw * scale)
            th = int(sh * scale)
            if tw <= 0 or th <= 0: continue
            
            img = src.copy()
            from PIL import ImageOps
            
            if item.get('totalRotation') is not None:
                tot_rot = float(item['totalRotation']) % 360
                is_odd_90 = (tot_rot % 180) != 0
                elem_tw = th if is_odd_90 else tw
                elem_th = tw if is_odd_90 else th
                
                if fit_mode == 'stretch':
                    img = img.resize((elem_tw, elem_th), Image.Resampling.LANCZOS)
                elif fit_mode == 'fill':
                    img = ImageOps.fit(img, (elem_tw, elem_th), method=Image.Resampling.LANCZOS)
                elif fit_mode == 'fit':
                    img = ImageOps.contain(img, (elem_tw, elem_th), method=Image.Resampling.LANCZOS)
                    bg = Image.new('RGB', (elem_tw, elem_th), (r, g, b))
                    bg.paste(img, ((elem_tw - img.width) // 2, (elem_th - img.height) // 2))
                    img = bg
                else:
                    img = img.resize((elem_tw, elem_th), Image.Resampling.LANCZOS)
                
                if tot_rot != 0:
                    img = img.rotate(-tot_rot, expand=True)
                if img.size != (tw, th):
                    img = ImageOps.fit(img, (tw, th), method=Image.Resampling.LANCZOS)
            else:
                # Legacy fallback
                if auto_rotate:
                    src_ratio = img.width / img.height
                    dst_ratio = tw / th
                    if (src_ratio > 1 and dst_ratio < 1) or (src_ratio < 1 and dst_ratio > 1):
                        img = img.rotate(-90, expand=True)
                
                if fit_mode == 'stretch':
                    img = img.resize((tw, th), Image.Resampling.LANCZOS)
                elif fit_mode == 'fill':
                    img = ImageOps.fit(img, (tw, th), method=Image.Resampling.LANCZOS)
                elif fit_mode == 'fit':
                    img = ImageOps.contain(img, (tw, th), method=Image.Resampling.LANCZOS)
                    bg = Image.new('RGB', (tw, th), (r, g, b))
                    bg.paste(img, ((tw - img.width) // 2, (th - img.height) // 2))
                    img = bg
                else:
                    img = img.resize((tw, th), Image.Resampling.LANCZOS)
                
                if is_flip_shape and item.get('rot', False):
                    img = img.rotate(180, expand=False)
                elif item.get('rot', False) and not is_flip_shape:
                    img = img.rotate(90, expand=True)
                    if img.size != (tw, th):
                        img = ImageOps.fit(img, (tw, th), method=Image.Resampling.LANCZOS)
            
            # Paste onto canvas
            x = int(item['x'] * scale)
            y = int(item['y'] * scale)
            try:
                canvas.paste(img, (x, y))
            except:
                pass
        
        # Draw grid lines (light gray)
        draw = ImageDraw.Draw(canvas)
        for item in plan_items:
            if is_flip_shape:
                sw, sh = item_w, effective_item_h
            elif item.get('rot', False):
                sw, sh = effective_item_h, item_w
            else:
                sw, sh = item_w, effective_item_h
            x1 = int(item['x'] * scale)
            y1 = int(item['y'] * scale)
            x2 = x1 + int(sw * scale)
            y2 = y1 + int(sh * scale)
            draw.rectangle([x1, y1, x2, y2], outline=(200, 200, 200), width=1)
        
        # Output as JPEG for speed
        buf = BytesIO()
        canvas.save(buf, format='JPEG', quality=85)
        buf.seek(0)
        
        return Response(buf.getvalue(), mimetype='image/jpeg',
                       headers={'Cache-Control': 'public, max-age=5'})
    
    except Exception as e:
        print(f"[PREVIEW] Error: {e}")
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/api/preview', methods=['POST'])
def api_preview():
    """Generate preview thumbnail"""
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No JSON data provided'}), 400
        
        image_bytes = render_preview_thumbnail(data)
        
        return Response(
            image_bytes,
            mimetype='image/png',
            headers={
                'Content-Disposition': 'inline; filename=preview.png'
            }
        )
        
    except Exception as e:
        print(f"[ERROR] Preview generation failed: {str(e)}")
        return jsonify({
            'error': 'Preview generation failed',
            'message': 'Không thể tạo preview',
            'details': str(e)
        }), 500

# Chunked upload storage
chunked_uploads = {}

@app.route('/api/init-chunked-upload', methods=['POST'])
def init_chunked_upload():
    """Initialize chunked upload"""
    try:
        data = request.get_json()
        filename = data.get('filename')
        file_size = data.get('file_size')
        
        if not filename or not file_size:
            return jsonify({'error': 'Missing filename or file_size'}), 400
        
        upload_id = str(uuid.uuid4())
        chunked_uploads[upload_id] = {
            'filename': filename,
            'file_size': file_size,
            'chunks': {},
            'created_at': time.time()
        }
        
        return jsonify({'upload_id': upload_id})
        
    except Exception as e:
        print(f"[ERROR] Init chunked upload failed: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/upload-chunk', methods=['POST'])
def upload_chunk():
    """Upload a single chunk"""
    try:
        upload_id = request.form.get('upload_id')
        chunk_index = int(request.form.get('chunk_index'))
        total_chunks = int(request.form.get('total_chunks'))
        
        if upload_id not in chunked_uploads:
            return jsonify({'error': 'Invalid upload_id'}), 400
        
        chunk_file = request.files.get('chunk')
        if not chunk_file:
            return jsonify({'error': 'No chunk file'}), 400
        
        # Store chunk data
        chunked_uploads[upload_id]['chunks'][chunk_index] = chunk_file.read()
        
        return jsonify({
            'success': True,
            'chunk_index': chunk_index,
            'total_chunks': total_chunks
        })
        
    except Exception as e:
        print(f"[ERROR] Upload chunk failed: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/finalize-upload', methods=['POST'])
def finalize_upload():
    """Finalize chunked upload and save complete file"""
    try:
        data = request.get_json()
        upload_id = data.get('upload_id')
        total_chunks = data.get('total_chunks')
        original_filename = data.get('original_filename')
        
        if upload_id not in chunked_uploads:
            return jsonify({'error': 'Invalid upload_id'}), 400
        
        upload_info = chunked_uploads[upload_id]
        
        # Check all chunks are present
        if len(upload_info['chunks']) != total_chunks:
            return jsonify({'error': 'Missing chunks'}), 400
        
        # Combine chunks
        os.makedirs(UPLOADS_DIR, exist_ok=True)
        file_path = os.path.join(UPLOADS_DIR, f"{uuid.uuid4()}_{original_filename}")
        
        with open(file_path, 'wb') as f:
            for i in range(total_chunks):
                if i in upload_info['chunks']:
                    f.write(upload_info['chunks'][i])
        
        # Clean up
        del chunked_uploads[upload_id]
        
        return jsonify({
            'success': True,
            'file_path': file_path,
            'filename': original_filename
        })
        
    except Exception as e:
        print(f"[ERROR] Finalize upload failed: {str(e)}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/outpaint-bleed', methods=['POST'])
def api_outpaint_bleed():
    """
    AI Bleed Outpainter endpoint using LaMa CPU model.
    Expands image borders (e.g. ~30%) to prevent bleed die-cutting issues.
    """
    try:
        from bleed_outpainter import get_bleed_outpainter
        from PIL import Image
        import io
        
        # Check for uploaded file or file_path in json/form
        uploaded_file = request.files.get('file') or request.files.get('image')
        file_path = request.form.get('file_path') or (request.json.get('file_path') if request.is_json else None)
        
        if uploaded_file:
            input_img = Image.open(uploaded_file.stream).convert('RGB')
        elif file_path and os.path.exists(file_path):
            input_img = Image.open(file_path).convert('RGB')
        else:
            return jsonify({'error': 'No file or valid file_path provided'}), 400
            
        percent = float(request.form.get('percent') or (request.json.get('percent', 0.30) if request.is_json else 0.30))
        bleed_mm = request.form.get('bleed_mm') or (request.json.get('bleed_mm') if request.is_json else None)
        bleed_mm = float(bleed_mm) if bleed_mm is not None else None
        dpi = int(request.form.get('dpi') or (request.json.get('dpi', 300) if request.is_json else 300))
        mode = request.form.get('mode') or (request.json.get('mode', 'smart_portrait') if request.is_json else 'smart_portrait')
        
        outpainter = get_bleed_outpainter()
        
        if bleed_mm is not None:
            out_img = outpainter.outpaint_for_print_card(input_img, bleed_mm=bleed_mm, dpi=dpi)
        else:
            out_img = outpainter.outpaint(input_img, bleed_percent=percent, pre_fill_method=mode)
            
        # Response format: 'image' (default) or 'json'
        response_format = request.args.get('format') or request.form.get('format') or (request.json.get('format') if request.is_json else 'image')
        
        if response_format == 'json':
            out_filename = f"bleed_{uuid.uuid4().hex[:8]}.jpg"
            out_path = os.path.join(UPLOADS_DIR, out_filename)
            out_img.save(out_path, quality=95)
            return jsonify({
                'success': True,
                'filename': out_filename,
                'file_path': out_path,
                'width': out_img.width,
                'height': out_img.height,
                'original_width': input_img.width,
                'original_height': input_img.height,
            })
        else:
            buf = io.BytesIO()
            out_img.save(buf, format='JPEG', quality=95)
            buf.seek(0)
            return Response(
                buf.getvalue(),
                mimetype='image/jpeg',
                headers={'Content-Disposition': 'inline; filename=outpaint_bleed.jpg'}
            )
    except Exception as e:
        logger.error(f"Outpaint API error: {e}")
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Store start time
    app.config['start_time'] = time.time()
    
    print("="*50)
    print("Python AI Service Starting...")
    print("="*50)
    print(f"Port: 3005")
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Upload folder: {UPLOADS_DIR}")
    print("="*50)
    
    # Run Flask app
    app.run(
        host='0.0.0.0',
        port=3005,
        debug=False,
        threaded=True
    )

@app.route('/api/export-pdf', methods=['POST'])
def api_export_pdf():
    """Export PDF for imposition"""
    try:
        # Handle file uploads and form data similar to generate-pdf
        files = []
        if 'file' in request.files:
            files = [request.files['file']]
        elif 'files' in request.files:
            files = request.files.getlist('files')
        
        # Get form data
        form_data = {}
        for key in request.form:
            try:
                form_data[key] = json.loads(request.form[key])
            except:
                form_data[key] = request.form[key]
        
        # Generate PDF using the same logic as generate-pdf
        if len(files) == 1:
            pdf_bytes = generate_pdf_from_request(files[0], form_data)
        else:
            pdf_bytes = generate_pdf_multipage_from_request(files, form_data)
        
        # Return PDF
        return Response(
            pdf_bytes,
            mimetype='application/pdf',
            headers={
                'Content-Disposition': 'attachment; filename=imposition_export.pdf',
                'Content-Length': len(pdf_bytes)
            }
        )
        
    except Exception as e:
        print(f"[ERROR] PDF export failed: {str(e)}")
        return jsonify({
            'error': 'PDF export failed',
            'message': 'Không thể xuất PDF',
            'details': str(e)
        }), 500

@app.route('/api/validate-file', methods=['POST'])
def api_validate_file():
    """Validate uploaded file"""
    try:
        if 'file' not in request.files:
            return jsonify({'error': 'No file uploaded'}), 400
        
        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No file selected'}), 400
        
        # Basic file validation
        allowed_extensions = {'.pdf', '.jpg', '.jpeg', '.png', '.tiff', '.tif'}
        file_ext = os.path.splitext(file.filename)[1].lower()
        
        if file_ext not in allowed_extensions:
            return jsonify({
                'error': 'Invalid file type',
                'message': f'File type {file_ext} không được hỗ trợ'
            }), 400
        
        # Check file size
        file.seek(0, 2)
        size = file.tell()
        file.seek(0)
        
        if size > 50 * 1024 * 1024:  # 50MB
            return jsonify({
                'error': 'File too large',
                'message': 'File quá lớn. Tối đa 50MB.'
            }), 413
        
        return jsonify({
            'success': True,
            'filename': file.filename,
            'size': size,
            'type': file_ext
        })
        
    except Exception as e:
        print(f"[ERROR] File validation failed: {str(e)}")
        return jsonify({
            'error': 'File validation failed',
            'details': str(e)
        }), 500

@app.route('/api/replace-images', methods=['POST'])
def api_replace_images():
    """Replace images in PDF"""
    try:
        # Placeholder implementation
        return jsonify({
            'success': True,
            'message': 'Image replacement completed'
        })
        
    except Exception as e:
        print(f"[ERROR] Image replacement failed: {str(e)}")
        return jsonify({
            'error': 'Image replacement failed',
            'details': str(e)
        }), 500
